### ISSUE TITLE
Reintroduce houdini_unescape_html

### ISSUE THREAD

**Issue by cfcommando** [reddit/snudown#65]
houdini.h declares a number of methods which are not implemented anywhere:

``` c
extern void houdini_escape_html(struct buf *ob, const uint8_t *src, size_t size);
extern void houdini_escape_html0(struct buf *ob, const uint8_t *src, size_t size, int secure);
extern void houdini_unescape_html(struct buf *ob, const uint8_t *src, size_t size);
extern void houdini_escape_xml(struct buf *ob, const uint8_t *src, size_t size);
extern void houdini_escape_uri(struct buf *ob, const uint8_t *src, size_t size);
extern void houdini_escape_url(struct buf *ob, const uint8_t *src, size_t size);
extern void houdini_escape_href(struct buf *ob, const uint8_t *src, size_t size);
extern void houdini_unescape_uri(struct buf *ob, const uint8_t *src, size_t size);
extern void houdini_unescape_url(struct buf *ob, const uint8_t *src, size_t size);
extern void houdini_escape_js(struct buf *ob, const uint8_t *src, size_t size);
extern void houdini_unescape_js(struct buf *ob, const uint8_t *src, size_t size);
```

I notice that houdini does have an implementation. but snudown does not. Could this method be re-added to snudown?
https://github.com/vmg/houdini/blob/master/houdini_html_u.c

**Comment by spladug** [comment]
Which specific ones are you looking for? The functions snudown itself needs are in `html/houdini_html_e.c` and `html/houdini_href_e.c`.  If additional ones that this library doesn't need are reqiured for your application, perhaps it'd be better to include the relevant bits of houdini directly there rather than adding dead code here?

**Comment by cfcommando** [comment]
Specifically, entity -> character resolution, i.e. `&amp;` -> `&` is that's missing.

**Comment by spladug** [comment]
Followup for posterity: discussed off-github and concluded that snudown can/should contain helper utilities for clients of the library and a pull request containing the rest of houdini + whatever else is currently needed would be accepted.

**Comment by JordanMilne** [comment]
We're planning on switching to a fork of CommonMark with our Reddit-specific extensions added to it. Since CommonMark automatically resolves HTML entities during parsing this will be fixed just by virtue of migrating.
