### ISSUE TITLE
can you please provide a sample example?

### ISSUE THREAD

**Issue by netdur** [reddit/snudown#77]
Hi, I'm trying to write Java binding to snudown, but I'm having problems understanding how snudown works, for example using heodown (which is also a sundown fork) I can do this:

    #include <string.h>
    #include <jni.h>
    #include "hoedown/html.h"

    JNIEXPORT jstring JNICALL
    Java_com_elmanahil_rdown_Rdown_render(JNIEnv* env, jobject that, jstring rdown) {
        const char *cdown = (*env)->GetStringUTFChars(env, rdown, NULL);
        const char *result = "";

        hoedown_renderer *renderer = hoedown_html_renderer_new(0, 0);
        hoedown_document *document = hoedown_document_new(renderer, 0, 16);
        hoedown_buffer *html = hoedown_buffer_new(16);
        hoedown_document_render(document, html, cdown, strlen(cdown));

        result = (const char*) html->data;

        hoedown_buffer_free(html);
        hoedown_document_free(document);
        hoedown_html_renderer_free(renderer);

        (*env)->NewStringUTF(env, result);
    }

what would be equivalent to above code in snudown?
thanks

**Comment by Pokechu22** [comment]
You should probably post this in [/r/redditdev](https://www.reddit.com/r/redditdev).  I don't think this issue tracker is commonly checked.

**Comment by kjoconnor** [comment]
Yep! Please post there instead. Thanks!

**Comment by netdur** [comment]
no problem, I have figured it out https://www.reddit.com/r/redditdev/comments/3n3mv0/android_snudown_java_binding_now_available/
